# -*- encoding: utf-8 -*-
from . import threaded_reports
from . import ir_attachment_drop
from . import hr_expense
from . import ir_ui_menu
from . import ir_sequence
from . import ir_actions_act_window_view
from . import ir_attachment
from . import account_invoice
from . import partner_category
from . import res_partner
from . import account_payment_term
from . import account_move
from . import account_move_line
from . import account_bank_statement_line
from . import account_move_line_sanity_check
from . import robo_usage
from . import product_product
from . import product_template
from . import account_analytic_line
from . import account_invoice_line
from . import account_invoice_tax
from . import cash_receipt
from . import res_users
from . import hr_employee
from . import hr_job
from . import hr_contract
from . import hr_contract_appointment
from . import resource_resource
from . import report_robo_report_employee_contract
from . import robo_upload
from . import mail_thread
from . import mail_message
from . import mail_template
from . import account_payment
from . import hr_department
from . import ir_actions_act_window
from . import ir_actions_act_window_settings
from . import ir_actions_actions
from . import ir_actions_client
from . import ir_actions_report_xml
from . import ir_actions_server
from . import ir_values
from . import robo_header
from . import robo_header_action_switcher
from . import robo_header_items
from . import hr_holidays
from . import robo_tour
from . import ir_http
from . import bank_statement
from . import periodic_invoice
from . import mail_mail
from . import ir_ui_view
from . import models
from . import category_mapping
from . import product_category
from . import client_support_ticket
from . import months
from . import project_project
from . import project_involvement
from . import account_analytic_group
from . import account_analytic_account
from . import account_invoice_report
from . import account_invoice_report_materialized
from . import res_company
from . import res_company_message
from . import res_company_vat_status
from . import account_analytic_default
from . import stock_picking
from . import analytic_account_budget_line
from . import periodic_front_bank_statement
from . import hr_employee_education_year
from . import hr_employee_education_year_schedule
from . import hr_employee_education_year_schedule_day
from . import account_invoice_tags
from . import account_invoice_tags_details
from . import robo_tools
from . import linksnis
from . import crm_team
from . import forecast_budget_line
from . import ir_module_module
from . import bank_integrations
from . import robo_import_job
from . import account_journal
from . import account_tax
from . import report_contract_termination_attachment
from . import report_overpay_transfer_request
from . import hr_employee_child