# -*- encoding: utf-8 -*-
# (c) 2021 Robolabs

{
    'name' : 'E Dokumentai',
    'version' : '1.0',
    'author' : 'Robolabs',
    'website': 'https://www.robolabs.lt',
    'license': 'Other proprietary',
    'category' : 'Documents',
    'description': """

==================================================================================
    """,
    'depends' : ['robo'],
    'demo' : [],
    'data' : [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/record.rules.xml',
        'data/header_buttons.xml',
        'views/main_views.xml',
        'data/header_button_items.xml',
        'data/cronjobs.xml',
        'data/mail_channels.xml',
        'views/document_menus.xml',
        'views/e_document_time_line_views.xml',
        'views/hr_employee_views.xml',
        'views/robo_views.xml',
        'data/dk.nutraukimo.straipsniai.csv',
        'data/import.xml',
        'data/sequence.xml',
        'report/report.xml',
        'wizard/mark_signed.xml',
        'wizard/robo_company_settings_views.xml',
        # 'wizard/automatic_wage_adjustment_document_settings_views.xml',
        'views/salary_views.xml',
        'views/pension_fund_transfer_views.xml',
        'wizard/e_document_import_views.xml',
        'wizard/pension_fund_transfer_document_import_views.xml',
        'wizard/bonus_document_import_views.xml',

        'templates/orders/e_document_order.xml',
        'templates/requests/e_document_request.xml',
        'templates/requests/del_darbo_sutarties_nutraukimo/del_darbo_sutarties_nutraukimo.xml',
        'templates/requests/del_isskaitu_is_darbo_uzmokescio/del_isskaitu_is_darbo_uzmokescio.xml',
        'templates/orders/del_isskaitu_is_darbo_uzmokescio/del_isskaitu_is_darbo_uzmokescio.xml',
        'templates/orders/del_darbuotojo_skyrimo_dirbti_poilsio_diena/del_darbuotojo_skyrimo_dirbti_poilsio_diena.xml',
        'templates/requests/suteikti_3_menesiu_atostogas_vaikui_priziureti/suteikti_3_menesiu_atostogas_vaikui_priziureti.xml',
        'templates/explanations/del_neatvykimo_i_darba/del_neatvykimo_i_darba.xml',
        'templates/orders/del_darbo_apmokejimo_padidinus_darbu_masta/del_darbo_apmokejimo_padidinus_darbu_masta.xml',
        'templates/requests/pakeisti_darbo_apmokejimo_salygas/pakeisti_darbo_apmokejimo_salygas.xml',
        'templates/orders/del_komandiruotes/del_komandiruotes.xml',
        'templates/orders/del_komandiruotes_grupei/del_komandiruotes_grupei.xml',
        'templates/orders/leisti_nedirbti_puse_dienos_pirmaja_mokslo_metu_diena/leisti_nedirbti_puse_dienos_pirmaja_mokslo_metu_diena.xml',
        'templates/requests/del_papildomos_lengvatos_auginant_vaikus_/del_papildomos_lengvatos_auginant_vaikus_.xml',
        'templates/orders/del_darbuotojo_skyrimo_dirbti_sventine_diena/del_darbuotojo_skyrimo_dirbti_sventine_diena.xml',
        'templates/requests/del_tarnybines_komandiruotes/del_tarnybines_komandiruotes.xml',
        'templates/orders/del_tarnybines_komandiruotes/del_tarnybines_komandiruotes.xml',
        'templates/requests/sugrizti_i_darba_nepasibaigus_motinystes_atostogoms/sugrizti_i_darba_nepasibaigus_motinystes_atostogoms.xml',
        'templates/requests/del_vaiko_prieziuros_atostogu_suteikimo/del_vaiko_prieziuros_atostogu_suteikimo.xml',
        'templates/requests/del_vaiko_prieziuros_atostogu_nutraukimo/del_vaiko_prieziuros_atostogu_nutraukimo.xml',
        'templates/orders/del_vaiko_prieziuros_atostogu/del_vaiko_prieziuros_atostogu.xml',
        'templates/orders/del_vaiko_prieziuros_atostogu_nutraukimo/del_vaiko_prieziuros_atostogu_nutraukimo.xml',
        'templates/orders/del_materialines_pasalpos_skyrimo/del_materialines_pasalpos_skyrimo.xml',
        'templates/requests/del_materialines_pasalpos_skyrimo/del_materialines_pasalpos_skyrimo.xml',
        'templates/orders/atleisti_nuo_darbo_valstybinems_visuomeninems_pareigoms_atlikti/atleisti_nuo_darbo_valstybinems_visuomeninems_pareigoms_atlikti.xml',
        'templates/requests/atleisti_nuo_darbo_valstybinems_visuomeninems_pareigoms_atlikti/atleisti_nuo_darbo_valstybinems_visuomeninems_pareigoms_atlikti.xml',
        'templates/orders/del_darbo_uzmokescio_pakeitimo/del_darbo_uzmokescio_pakeitimo.xml',
        'templates/orders/del_paskyrimo_laikinai_eiti_pareigas/del_paskyrimo_laikinai_eiti_pareigas.xml',
        'templates/orders/del_nestumo_ir_gimdymo_atostogu/del_nestumo_ir_gimdymo_atostogu.xml',
        'templates/requests/del_nestumo_ir_gimdymo_atostogu/del_nestumo_ir_gimdymo_atostogu.xml',
        'templates/orders/del_poilsio_dienos_perkelimo/del_poilsio_dienos_perkelimo.xml',
        'templates/orders/del_darbo_sutarties_salygu_pakeitimo/del_darbo_sutarties_salygu_pakeitimo.xml',
        'templates/orders/del_papildomu_atostogu/del_papildomu_atostogu.xml',
        'templates/requests/del_papildomu_atostogu/del_papildomu_atostogu.xml',
        'templates/orders/del_papildomos_lengvatos_suteikimo/del_papildomos_lengvatos_suteikimo.xml',
        'templates/requests/del_darbo_uzmokescio_pervedimo_i_banko_saskaita/del_darbo_uzmokescio_pervedimo_i_banko_saskaita.xml',
        'templates/requests/perkelti_kasmetiniu_atostogu_dali/perkelti_kasmetiniu_atostogu_dali.xml',
        'templates/orders/del_nemokamu_atostogu/del_nemokamu_atostogu.xml',
        'templates/requests/del_nemokamu_atostogu_suteikimo/del_nemokamu_atostogu_suteikimo.xml',
        'templates/orders/del_mokymosi_atostogu_dalyvauti_neformaliojo_suaugusiuju_svietimo_programose/del_mokymosi_atostogu_dalyvauti_neformaliojo_suaugusiuju_svietimo_programose.xml',
        'templates/orders/del_mokymosi_atostogu/del_mokymosi_atostogu.xml',
        'templates/orders/del_3_menesiu_atostogu_vaikui_priziureti_suteikimo/del_3_menesiu_atostogu_vaikui_priziureti_suteikimo.xml',
        'templates/orders/laisvos_formos_isakymas/laisvos_formos_isakymas.xml',
        'templates/requests/apmoketi_kasmetines_atostogas_kartu_su_darbo_uzmokesciu/apmoketi_kasmetines_atostogas_kartu_su_darbo_uzmokesciu.xml',
        'templates/orders/del_priemimo_i_darba/del_priemimo_i_darba.xml',
        'templates/requests/del_priemimo_i_darba_ir_atlyginimo_mokejimo/del_priemimo_i_darba_ir_atlyginimo_mokejimo.xml',
        'templates/orders/del_naudojamo_ligos_koeficiento/del_naudojamo_ligos_koeficiento.xml',
        'templates/orders/del_terminuotos_darbo_sutarties_pasibaigimo_ir_darbo_santykiu_tesimo_pagal_neterminuota_darbo_sutarti/del_terminuotos_darbo_sutarties_pasibaigimo_ir_darbo_santykiu_tesimo_pagal_neterminuota_darbo_sutarti.xml',
        'templates/orders/del_mamadienio___tevadienio_suteikimo/del_mamadienio___tevadienio_suteikimo.xml',
        'templates/requests/del_mamadienio___tevadienio_suteikimo/del_mamadienio___tevadienio_suteikimo.xml',
        'templates/requests/del_darbo_grafiko_pakeitimo/del_darbo_grafiko_pakeitimo.xml',
        'templates/orders/del_darbo_grafiko_pakeitimo/del_darbo_grafiko_pakeitimo.xml',
        'templates/requests/nedirbti_puse_dienos_pirmaja_mokslo_metu_diena/nedirbti_puse_dienos_pirmaja_mokslo_metu_diena.xml',
        'templates/requests/del_neapmokestinamojo_pajamu_dydzio_taikymo/del_neapmokestinamojo_pajamu_dydzio_taikymo.xml',
        'templates/requests/del_neapmokestinamojo_pajamu_dydzio_taikymo_neigaliesiems/del_neapmokestinamojo_pajamu_dydzio_taikymo_neigaliesiems.xml',
        'templates/requests/del_kasmetiniu_atostogu/del_kasmetiniu_atostogu.xml',
        'templates/orders/del_kasmetiniu_atostogu/del_kasmetiniu_atostogu.xml',
        'templates/orders/del_poilsio_dienos_suteikimo/del_poilsio_dienos_suteikimo.xml',
        'templates/requests/del_poilsio_dienos_suteikimo/del_poilsio_dienos_suteikimo.xml',
        'templates/requests/del_kvalifikacijos_kelimo/del_kvalifikacijos_kelimo.xml',
        'templates/orders/del_kvalifikacijos_kelimo/del_kvalifikacijos_kelimo.xml',
        'templates/orders/del_kvalifikacijos_tobulinimo/del_kvalifikacijos_tobulinimo.xml',
        'templates/orders/del_nuobaudos_skyrimo/del_nuobaudos_skyrimo.xml',
        'templates/orders/del_papildomos_poilsio_dienos_suteikimo/del_papildomos_poilsio_dienos_suteikimo.xml',
        'templates/requests/del_papildomos_poilsio_dienos_suteikimo/del_papildomos_poilsio_dienos_suteikimo.xml',
        'templates/orders/del_papildomos_poilsio_dienos_suteikimo_atsaukimo/del_papildomos_poilsio_dienos_suteikimo_atsaukimo.xml',
        'templates/requests/suteikti_mokymosi_atostogas/suteikti_mokymosi_atostogas.xml',
        'templates/requests/suteikti_mokymosi_atostogas_dalyvauti_neformaliojo_suaugusiuju_svietimo_programose/suteikti_mokymosi_atostogas_dalyvauti_neformaliojo_suaugusiuju_svietimo_programose.xml',
        'templates/orders/del_kurybiniu_atostogu_suteikimo/del_kurybiniu_atostogu_suteikimo.xml',
        'templates/requests/del_pavardes_pakeitimo/del_pavardes_pakeitimo.xml',
        'templates/requests/del_darbo_uzmokescio_mokejimo/del_darbo_uzmokescio_mokejimo.xml',
        'templates/orders/del_darbo_uzmokescio_mokejimo/del_darbo_uzmokescio_mokejimo.xml',
        'templates/orders/del_priedo_skyrimo_grupei/del_priedo_skyrimo_grupei.xml',
        'templates/orders/dynamic_workplace_compensation/dynamic_workplace_compensation.xml',
        'templates/orders/group_dynamic_workplace_compensation/group_dynamic_workplace_compensation.xml',
        'templates/orders/OLD_del_kompensacijos_uz_kilnojamojo_pobudzio_darba_skyrimo/del_kompensacijos_uz_kilnojamojo_pobudzio_darba_skyrimo.xml',
        'templates/orders/del_sumos_nuo_kurios_sanaudos_laikomos_ilgalaikiu_turtu/del_sumos_nuo_kurios_sanaudos_laikomos_ilgalaikiu_turtu.xml',
        'templates/requests/suteikti_tevystes_atostogas/suteikti_tevystes_atostogas.xml',
        'templates/requests/laisvos_formos_prasymas/laisvos_formos_prasymas.xml',
        'templates/orders/del_priedo_skyrimo/del_priedo_skyrimo.xml',
        'templates/requests/suteikti_kurybines_atostogas/suteikti_kurybines_atostogas.xml',
        'templates/orders/del_periodinio_priedo_skyrimo/del_periodinio_priedo_skyrimo.xml',
        'templates/orders/del_periodinio_priedo_atsaukimo/del_periodinio_priedo_atsaukimo.xml',
        'templates/orders/del_pavardes_keitimo/del_pavardes_keitimo.xml',
        'templates/requests/leisti_neatvykti_i_darba/leisti_neatvykti_i_darba.xml',
        'templates/orders/del_pastabos_skyrimo/del_pastabos_skyrimo.xml',
        'templates/orders/del_bendroves_kasininko_paskyrimo/del_bendroves_kasininko_paskyrimo.xml',
        'templates/orders/del_atleidimo_is_darbo/del_atleidimo_is_darbo.xml',
        'templates/requests/del_perkelimo_i_kita_darbo_vieta/del_perkelimo_i_kita_darbo_vieta.xml',
        'templates/requests/del_pareigybes_keitimo/del_pareigybes_keitimo.xml',
        'templates/orders/del_pareigybes_keitimo/del_pareigybes_keitimo.xml',
        'templates/orders/del_ankstesnio_vadovo_isakymo_panaikinimo/del_ankstesnio_vadovo_isakymo_panaikinimo.xml',
        'templates/orders/del_kasos_darbo_organizavimo/del_kasos_darbo_organizavimo.xml',
        'templates/orders/del_skatinimo_/del_skatinimo_.xml',
        'templates/orders/del_atsaukimo_is_kasmetiniu_atostogu/del_atsaukimo_is_kasmetiniu_atostogu.xml',
        'templates/orders/del_leidimo_neatvykti_i_darba/del_leidimo_neatvykti_i_darba.xml',
        'templates/messages/apie_darbo_sutarties_vykdymo_sustabdyma/apie_darbo_sutarties_vykdymo_sustabdyma.xml',
        'templates/orders/del_premijos_skyrimo/del_premijos_skyrimo.xml',
        'templates/orders/del_tevystes_atostogu_suteikimo/del_tevystes_atostogu_suteikimo.xml',
        'templates/shareholders_decisions/shareholders_decisions_views.xml',
        'templates/shareholders_decisions/del_vadovo_pakeitimo/del_vadovo_pakeitimo.xml',
        'templates/shareholders_decisions/del_akcininku_sprendimo_panaikinimo/del_akcininku_sprendimo_panaikinimo.xml',
        'templates/acts/acts.xml',
        'templates/acts/kuro_nurasymas/kuro_nurasymas.xml',
        'templates/orders/del_prastovos_skelbimo/del_prastovos_skelbimo.xml',
        'templates/orders/del_prastovos_nutraukimo/del_prastovos_nutraukimo.xml',
        'templates/orders/del_ligos_pasalpai_taikomo_procento/del_ligos_pasalpai_taikomo_procento.xml',
        'templates/agreements/e_document_agreement.xml',
        'templates/agreements/voluntary_internship/voluntary_internship.xml',
        'templates/agreements/personal_asset_usage/personal_asset_usage.xml',
        'templates/acts/pravaikstos_skyrimas/pravaikstos_skyrimas.xml',
        'wizard/invite_to_sign.xml',
        'templates/requests/del_kasmetiniu_atostogu_atsaukimo/del_kasmetiniu_atostogu_atsaukimo.xml',
        'templates/orders/del_neatvykimo_i_darba_darbdaviui_leidus/del_neatvykimo_i_darba_darbdaviui_leidus.xml',
        'templates/orders/del_priedo_skyrimo_grupei_pagal_darbo_laika/del_priedo_skyrimo_grupei_pagal_darbo_laika.xml',
        'templates/orders/del_nepanaudotu_atostogu_anuliavimo/del_nepanaudotu_atostogu_anuliavimo.xml',
        'templates/other/laisvos_formos_dokumentas/laisvos_formos_dokumentas.xml',
        'templates/requests/remote_work/remote_work.xml',
        'templates/agreements/remote_work/remote_work.xml',
        'templates/requests/del_etato_keitimo/del_etato_keitimo.xml',
        'templates/other/compensation_certificate/compensation_certificate.xml',
        'templates/requests/overtime/overtime.xml',
        'templates/orders/overtime/overtime.xml',
        'templates/requests/work_during_absence/work_during_absence.xml',
        'templates/orders/work_during_absence/work_during_absence.xml',
        'templates/orders/del_susitarimo_nutraukimo/del_susitarimo_nutraukimo.xml',
        'templates/requests/unpaid_free_time/unpaid_free_time.xml',
        'templates/orders/unpaid_free_time/unpaid_free_time.xml',
        'templates/orders/pension_payment/pension_payment.xml',
        'templates/agreements/asset_lease/asset_lease.xml',
        'templates/agreements/end_agreement/end_agreement.xml',
        'templates/requests/request_holiday_extension/request_holiday_extension.xml',
        'templates/orders/order_holiday_extension/order_holiday_extension.xml',
        'templates/orders/internship/internship.xml',
        'templates/requests/request_work_schedule_change/request_work_schedule_change.xml',
    ],
    'qweb': ['static/src/xml/*.xml',],
    'auto_install': False,
    'installable': True,
}