# -*- coding: utf-8 -*-

PRODUCT_TYPES = [
    ('apmokestinamasGaminys', 'Gaminys'),
    ('alyvosGaminys', 'Alyva'),
    ('elektronineIranga', 'Elektroninė įranga'),
    ('transportoPriemone', 'Transporto priemonė'),
    ('prekinisVienetas', 'Prekinis vienetas'),
    #('baterija', 'Baterija'),
]


MATERIAL_TYPE_CODE_MAPPING = {
    'stiklas': '1',
    'plastikas': '2',
    'kombinuota': '3',
    'metalas': '4',
    'popierius': '5',
    'kita': '6',
    'pet': '7',
    'medis': '8',
    'kombinuota_kita': '9',
    'kombinuota_kita_vyr_stiklas': '9-01',
}

PAKUOTE_RUSIS = [
    ('01', '01 - Stiklinė tuščia'),
    ('02', '02 - Plastikinė tuščia'),
    ('03', '03 - Kombinuota (popierinė) tuščia'),
    ('04', '04 - Metalinė tuščia'),
    ('05', '05 - Popierinė ir kartoninė tuščia'),
    ('06', '06 - Kita tuščia'),
    ('07', '07 - PET tuščia'),
    ('08', '08 - Medinė tuščia'),
    ('09', '09 - Kombinuota (kita) tuščia'),
    ('09-01', '09-01 - Kombinuota tuščia kita (vyraujanti stiklas)'),
    ('11', '11 - Stiklinė pirminė'),
    ('12', '12 - Plastikinė pirminė'),
    ('13', '13 - Kombinuota (popierinė) pirminė'),
    ('14', '14 - Metalinė pirminė'),
    ('15', '15 - Popierinė ir kartoninė pirminė'),
    ('16', '16 - Kita pirminė'),
    ('17', '17 - PET pirminė'),
    ('18', '18 - Medinė pirminė'),
    ('19', '19 - Kombinuota (kita) pirminė'),
    ('21', '21 - Stiklinė antrinė (tretinė)'),
    ('22', '22 - Plastikinė antrinė (tretinė)'),
    ('23', '23 - Kombinuota (popierinė) antrinė (tretinė)'),
    ('24', '24 - Metalinė antrinė (tretinė)'),
    ('25', '25 - Popierinė ir kartoninė antrinė (tretinė)'),
    ('26', '26 - Kita antrinė (tretinė)'),
    ('27', '27 - PET antrinė (tretinė)'),
    ('28', '28 - Medinė antrinė (tretinė)'),
    ('29', '29 - Kombinuota (kita) antrinė (tretinė)'),
    ('31', '31 - Stiklinė pirminė / užstatinė daugkartinė '),
    ('32', '32 - Plastikinė pirminė daugkartinė'),
    ('33', '33 - Kombinuota (popierinė) pirminė daugkartinė'),
    ('34', '34 - Metalinė pirminė daugkartinė'),
    ('35', '35 - Popierinė (kartoninė) pirminė daugkartinė'),
    ('36', '36 - Kita pirminė daugkartinė'),
    ('37', '37 - PET pirminė daugkartinė'),
    ('38', '38 - Medinė pirminė daugkartinė'),
    ('39', '39 - Kombinuota (kita) pirminė daugkartinė'),
    ('41', '41 - Stiklinė antrinė (tretinė) daugkartinė'),
    ('42', '42 - Plastikinė antrinė (tretinė) daugkartinė'),
    ('43', '43 - Kombinuota (popierinė) antrinė (tretinė) daugkartinė'),
    ('44', '44 - Metalinė antrinė (tretinė) daugkartinė'),
    ('45', '45 - Popierinė ir kartoninė antrinė (tretinė) daugkartinė'),
    ('46', '46 - Kita antrinė (tretinė) daugkartinė'),
    ('47', '47 - PET antrinė (tretinė) daugkartinė'),
    ('48', '48 - Medinė antrinė (tretinė) daugkartinė'),
    ('49', '49 - Kombinuota (kita) antrinė (tretinė) daugkartinė'),
    ('51', '51 - Stiklinė užstatinė'),
    ('54', '54 - Metalinė užstatinė'),
    ('57', '57 - PET užstatinė'),
    ('61', '61 - Stiklinė pirminė sunaudota savoms reikmėms'),
    ('62', '62 - Plastikinė pirminė sunaudota savoms reikmėms'),
    ('63', '63 - Kombinuota (popierinė) pirminė sunaudota savoms reikmėms'),
    ('64', '64 - Metalinė pirminė sunaudota savoms reikmėms'),
    ('65', '65 - Popierinė (kartoninė) pirminė sunaudota savoms reikmėms'),
    ('66', '66 - Kita pirminė sunaudota savoms reikmėms'),
    ('67', '67 - PET pirminė sunaudota savoms reikmėms'),
    ('68', '68 - Medinė pirminė sunaudota savoms reikmėms'),
    ('69', '69 - Kombinuota (kita) pirminė sunaudota savoms reikmėms'),
    ('71', '71 - Stiklinė antrinė (tretinė) sunaudota savoms reikmėms'),
    ('72', '72 - Plastikinė antrinė (tretinė) sunaudota savoms reikmėms'),
    ('73', '73 - Kombinuota (popierinė) antrinė (tretinė) sunaudota savoms reikmėms'),
    ('74', '74 - Metalinė antrinė (tretinė) sunaudota savoms reikmėms'),
    ('75', '75 - Popierinė (kartoninė) antrinė (tretinė) sunaudota savoms reikmėms'),
    ('76', '76 - Kita antrinė (tretinė) sunaudota savoms reikmėms'),
    ('77', '77 - PET antrinė (tretinė) sunaudota savoms reikmėms'),
    ('78', '78 - Medinė antrinė (tretinė) sunaudota savoms reikmėms'),
    ('79', '79 - Kombinuota (kita) antrinė (tretinė) sunaudota savoms reikmėms')
]


veiklosBudas_mapping = {
    'CL118:DP:2016-12-07': 'b2b',
    'CL118:MP:2016-12-07': 'b2c',
    'CL118:NP:2016-12-07': 'remote',
    'CL118:ET:2016-12-07': 'export_broker',
    'CL118:EV:2016-12-07': 'export',
    'CL118:SS:2016-12-07': 'own_need',
}
