# -*- encoding: utf-8 -*-
# (c) 2021 Robolabs
{
    'name': 'Sepa Importavimas',
    'author': 'Robolabs',
    'category': 'Accounting & Finance',
    'license': 'Other proprietary',
    'depends': ['base_iban', 'robo_basic'],
    'demo': [],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ir_config_parameter_data.xml',
        'data/ir_cron.xml',
        'data/ir_sequence.xml',
        'view/settings.xml',
        'view/sepa_wizard.xml',
        'view/account_bank_statement_line_views.xml',
        'view/account_bank_statement_views.xml',
        'view/account_journal_views.xml',
        'view/banking_circle.xml',
        'view/bitsafe.xml',
        'view/coingate.xml',
        'view/payally.xml',
        'view/payoneer.xml',
        'view/paypal.xml',
        'view/transferwise.xml',
        'view/revolut.xml',
        'view/revolut_api_views.xml',
        'view/revolut_api_transaction_views.xml',
        'view/revolut_api_transaction_leg_views.xml',
        'view/revolut_account_views.xml',
        'view/mypos.xml',
        'view/mistertango.xml',
        'view/globalnet.xml',
        'view/opay.xml',
        'view/stripe.xml',
        'view/skrill.xml',
        'view/luminor.xml',
        'view/nexpay.xml',
        'view/swedbank_api.xml',
        'view/api_menus.xml',
        'view/bank_export_job.xml',
        'view/worldfirst.xml',
        'view/walletto.xml',
        'view/soldo.xml',
        'view/bank_statement_fetch_job_views.xml',
        'wizard/revolut_api_import_views.xml',
        'wizard/api_query_bank_statements_wizard.xml',
        'wizard/bank_statement_balance_recalculation_wizard_views.xml',
        # Paysera views
        'paysera_api/view/paysera_configuration.xml',
        'paysera_api/view/paysera_wallet.xml',
        'paysera_api/view/paysera_wallet_iban.xml',
        'paysera_api/wizard/paysera_payment_transfer_wizard.xml',
        'paysera_api/data/ir_cron.xml',

        # SEB views/data
        'seb_api/data/ir_cron_data.xml',
        'seb_api/data/ir_config_parameter_data.xml',
        'seb_api/view/seb_configuration_views.xml',
        'seb_api/view/seb_api_journal_views.xml',
        'seb_api/wizard/seb_payment_transfer_wizard_views.xml',

        # EnableBanking views/data
        'enable_banking_api/data/enable_banking_configuration_data.xml',
        'enable_banking_api/data/enable_banking_connector_data.xml',
        'enable_banking_api/data/ir_config_parameter_data.xml',
        'enable_banking_api/data/ir_cron_data.xml',
        'enable_banking_api/view/enable_banking_configuration_views.xml',
        'enable_banking_api/view/enable_banking_connector_views.xml',
        'enable_banking_api/view/enable_banking_account_views.xml',
        'enable_banking_api/security/ir.model.access.csv',

        # Braintree views/data
        'braintree_api/data/ir_sequence.xml',
        'braintree_api/data/ir_cron.xml',
        'braintree_api/views/braintree_configuration_views.xml',
        'braintree_api/views/braintree_gateway_views.xml',
        'braintree_api/views/braintree_merchant_account_views.xml',
        'braintree_api/views/braintree_transaction_views.xml',
        'braintree_api/views/braintree_customer_views.xml',
        'braintree_api/security/ir.model.access.csv',
    ],
    'auto_install': False,
    'installable': True,
}
