# -*- coding: utf-8 -*-
from . import nsoft_tools
from . import account_invoice
from . import account_invoice_line
from . import nsoft_cash_register
from . import nsoft_invoice
from . import nsoft_invoice_line
from . import nsoft_payment_alt_names
from . import nsoft_payment_type
from . import nsoft_sale_line
from . import nsoft_payment
from . import nsoft_receipt_report
from . import nsoft_cash_operation
from . import product_template
from . import res_company
from . import robo_company_settings
from . import sum_accounting
from . import account_tax
from . import res_partner
from . import nsoft_cashier_mapper
from . import account_payment
from . import nsoft_import_base
