from . import atleisti_nuo_darbo_valstybinems_visuomeninems_pareigoms_atlikti
from . import del_3_menesiu_atostogu_vaikui_priziureti_suteikimo
from . import del_ankstesnio_vadovo_isakymo_panaikinimo
from . import del_atleidimo_is_darbo
from . import del_atsaukimo_is_kasmetiniu_atostogu
from . import del_bendroves_kasininko_paskyrimo
from . import del_darbo_apmokejimo_padidinus_darbu_masta
from . import del_darbo_grafiko_pakeitimo
from . import del_darbo_sutarties_salygu_pakeitimo
from . import del_darbo_uzmokescio_mokejimo
from . import del_darbo_uzmokescio_pakeitimo
from . import del_darbuotojo_skyrimo_dirbti_poilsio_diena
from . import del_darbuotojo_skyrimo_dirbti_sventine_diena
from . import del_isskaitu_is_darbo_uzmokescio
from . import del_kasmetiniu_atostogu
from . import del_kasos_darbo_organizavimo
from . import del_komandiruotes
from . import del_komandiruotes_grupei
from . import del_kurybiniu_atostogu_suteikimo
from . import del_kvalifikacijos_kelimo
from . import del_kvalifikacijos_tobulinimo
from . import del_leidimo_neatvykti_i_darba
from . import del_mamadienio___tevadienio_suteikimo
from . import del_materialines_pasalpos_skyrimo
from . import del_mokymosi_atostogu
from . import del_mokymosi_atostogu_dalyvauti_neformaliojo_suaugusiuju_svietimo_programose
from . import del_naudojamo_ligos_koeficiento
from . import del_nemokamu_atostogu
from . import del_nestumo_ir_gimdymo_atostogu
from . import del_nuobaudos_skyrimo
from . import del_papildomos_lengvatos_suteikimo
from . import del_papildomos_poilsio_dienos_suteikimo
from . import del_papildomos_poilsio_dienos_suteikimo_atsaukimo
from . import del_papildomu_atostogu
from . import del_pareigybes_keitimo
from . import del_paskyrimo_laikinai_eiti_pareigas
from . import del_pastabos_skyrimo
from . import del_pavardes_keitimo
from . import del_poilsio_dienos_perkelimo
from . import del_poilsio_dienos_suteikimo
from . import del_premijos_skyrimo
from . import del_priedo_skyrimo
from . import del_priedo_skyrimo_grupei
from . import del_periodinio_priedo_atsaukimo
from . import del_periodinio_priedo_skyrimo
from . import del_priemimo_i_darba
from . import del_skatinimo_
from . import del_sumos_nuo_kurios_sanaudos_laikomos_ilgalaikiu_turtu
from . import del_tarnybines_komandiruotes
from . import del_terminuotos_darbo_sutarties_pasibaigimo_ir_darbo_santykiu_tesimo_pagal_neterminuota_darbo_sutarti
from . import del_tevystes_atostogu_suteikimo
from . import del_vaiko_prieziuros_atostogu
from . import del_vaiko_prieziuros_atostogu_nutraukimo
from . import laisvos_formos_isakymas
from . import leisti_nedirbti_puse_dienos_pirmaja_mokslo_metu_diena
from . import del_prastovos_skelbimo
from . import del_prastovos_nutraukimo
from . import del_ligos_pasalpai_taikomo_procento
from . import OLD_del_kompensacijos_uz_kilnojamojo_pobudzio_darba_skyrimo
from . import del_neatvykimo_i_darba_darbdaviui_leidus
from . import del_priedo_skyrimo_grupei_pagal_darbo_laika
from . import del_nepanaudotu_atostogu_anuliavimo
from . import dynamic_workplace_compensation
from . import group_dynamic_workplace_compensation
from . import overtime
from . import work_during_absence
from . import del_susitarimo_nutraukimo
from . import unpaid_free_time
from . import pension_payment
from . import internship
from . import order_holiday_extension
