# -*- encoding: utf-8 -*-
# (c) 2021 Robolabs

{
    'name': 'Robo stock',
    'author': 'Robolabs',
    'website': 'http://www.robolabs.lt',
    'license': 'Other proprietary',
    'category': 'Misc',
    'depends': ['nurasymo_aktas', 'stock_move_report'],
    'demo': [],
    'data': [
        'security/groups.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'data/header_buttons.xml',
        'data/account_journal_data.xml',
        'data/stock_reason_line_data.xml',
        'data/ir_cron_data.xml',
        'view/product_attribute.xml',
        'view/product_product.xml',
        'view/robo_stock.xml',
        'view/stock_inventory.xml',
        'view/stock_picking_views.xml',
        'view/reports.xml',
        'view/import_quants.xml',
        'view/account_invoice_views.xml',
        'view/periodic_invoice_views.xml',
        'view/account_invoice_report.xml',
        'view/stock_move.xml',
        'view/procurement_rule.xml',
        'view/procurement_order.xml',
        'view/hr_department.xml',
        'view/res_users.xml',
        'view/stock_location.xml',
        'view/stock_location_path.xml',
        'view/stock_location_route.xml',
        'view/stock_warehouse_orderpoint.xml',
        'view/advanced_stock_location_menus.xml',
        'view/product_supplierinfo.xml',
        'view/stock_reason_line_views.xml',
        'wizard/order_done_warning_wizard.xml',
        'wizard/stock_inventory_adjustment_confirmation_wizard.xml',
        'wizard/stock_inventory_import_views.xml',
        'data/header_buttons_items.xml',
        'data/robo_action_settings.xml',
    ],
    'qweb': ['static/src/xml/*.xml'],
    'auto_install': False,
    'installable': True,
    'uninstall_hook': 'uninstall_hook',
}
