# -*- encoding: utf-8 -*-
import account_asset_asset
import account_asset_category
import account_asset_change_line
import account_asset_depreciation_line
import account_asset_responsible
import account_asset_revaluation_history
import account_invoice
import account_invoice_line
import account_move
import res_company
import account_asset_department
import robo_company_settings
