# -*- encoding: utf-8 -*-

from . import work_schedule
from . import work_schedule_line
from . import work_schedule_day 
from . import work_schedule_day_line 
from . import work_schedule_holidays 
from . import work_schedule_parameters
from . import res_company
from . import res_users
from . import schedule_line_view
from . import dk_constraints
from . import ziniarastis_period
from . import ziniarastis_period_line
from . import ziniarastis_day
from . import schedule_template
from . import work_norm 
from . import hr_holidays
from . import hr_employee
from . import hr_employee_compensation
from . import hr_contract
from . import hr_employee_overtime
from . import hr_employee_overtime_time_line
from . import hr_employee_forced_work_time
from . import ir_actions_act_window_view
from . import ir_ui_view
from . import hr_payslip
from . import work_schedule_codes
from . import res_company_extended_schedule_period
from . import hr_payslip_worked_days
from . import e_document
from . import hr_contract_appointment
