# -*- encoding: utf-8 -*-
from . import expenses_wizard
from . import print_contract_wizard
from . import account_invoice_tax_change_wizard
from . import res_users_chart_settings
from . import account_invoice_partner_change_wizard
from . import analytic_wizard
from . import account_invoice_type_change_wizard
from . import invoice_mass_mailing
from . import account_financial_report_addition_wizard
from . import start_employee_internship
from . import reports
from . import report_invoice_processing_issue
from . import client_support_ticket_wizard
from . import account_invoice_number_wizard
from . import ap_employee_select_wizard
from . import cash_receipt_number_wizard
from . import invoice_change_line_wizard
from . import invoice_change_tax_line_wizard
from . import mail_compose_message
from . import needaction_accountant_wizard
from . import needaction_ceo_wizard
from . import account_invoice_refund
from . import register_payment
from . import account_analytic_account_filter_wizard
from . import robo_company_settings
from . import robo_company_settings_bank
from . import account_aged_trial_balance
from . import account_common_partner_report
from . import accounting_report
from . import invoice_registry_wizard
from . import payslips_report_wizard
from . import timesheets_report_wizard
from . import employee_count_report
from . import ir_attachment_wizard
from . import robo_mail_compose_message
from . import robo_mail_mass_mailing_partners
from . import debt_act_wizard
from . import invoice_financial_account_change_wizard
from . import e_vmi_gpm312
from . import account_report_general_ledger
from . import front_bank_statement_merge_wizard
from . import invoice_date_change_wizard
from . import overpay_transfer_request_wizard
from . import mail_channel_subscriptions_wizard
from . import account_invoice_vat_change_wizard
from . import change_user_partner_of_employee_wizard
