# -*- encoding: utf-8 -*-
# (c) 2021 Robolabs

{
    'name' : 'El. ataskaitos',
    'version' : '1.0',
    'author' : 'Robolabs',
    'website': 'http://www.robolabs.lt',
    'license': 'Other proprietary',
    'category' : 'Reporting',
    'depends' : ['l10n_lt_payroll', 'sl_intrastat', 'saskaitos'],
    'demo' : [],
    'data' : ['view/VMI.xml',
              'view/IVAZ.xml',
              'view/e_statistika.xml',
              'view/fr0600_report_views.xml',
              'wizard/FR0438/e_vmi_fr0438.xml',
              'wizard/FR0521/e_vmi_fr0521.xml',
              'wizard/GPM312/gpm312_report.xml',
              'wizard/GPM312/e_vmi_gpm312.xml',
              'wizard/FR0573/fr_0573_report.xml',
              'wizard/FR0573/e_vmi_fr0573.xml',
              'wizard/FR0573/fr_0573_data_import.xml',
              'wizard/SAFT/vmi_saf_t.xml',
              'view/VMI_menuitems.xml',
              'view/company.xml',
              'view/stock_picking.xml',
              'view/saf_t_tax_table_views.xml',
              'view/saf_t_account_views.xml',
              'view/account_account_views.xml',
              'data/evrk.kodai.csv',
              'data/saf.t.account.csv',
              'data/saf.t.tax.table.csv',
              'security/ir.model.access.csv',
    ],
    'auto_install': False,
    'installable': True,
}
