# -*- coding: utf-8 -*-
{
    'name': "Amazon Integration",
    'summary': """""",
    'description': """Amazon integration""",
    'author': "RoboLabs",
    'website': "http://www.robolabs.lt",
    'category': '',
    'license': 'Other proprietary',
    'version': '1.0',
    'depends': ['robo'],
    'data': [
        'data/cron_jobs.xml',
        'data/amazon_marketplace.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/amazon_product.xml',
        'data/amazon_region.xml',
        'security/ir.model.access.csv',
        'view/amazon_order.xml',
        'view/amazon_marketplace.xml',
        'view/amazon_product.xml',
        'view/amazon_product_category.xml',
        'view/amazon_order_report.xml',
        'view/amazon_region.xml',
        'wizard/amazon_import_wizard.xml',
        'wizard/amazon_configuration_wizard.xml',
        'wizard/robo_company_settings.xml',
        'view/amazon_import_wizard_job.xml',
        'view/menus.xml',
    ],
    'qweb': [],
    'css': [],
    'demo': [],
    'installable': True,
}